---
author: Nicole Brewer
authors: []
categories: []
date: "2020-07-18"
featured: false
image:
  caption: ""
  focal_point: ""
  preview_only: false
lastmod: "2020-07-18T19:33:51-04:00"
projects: []
slug: long-tales-of-science
subtitle: ""
summary: ""
tags:
- WHPC
- Long Tales of Science Podcast
title: Long Tales of Science
---

Women in HPC at Purdue is proud to present the Long Tales of Science Podcast, where we interview women in science, engineering, social science, and the humanities who use supercomputers to empower their research. Today I want to take about the origin story of the the podcast's namesake. The term long tail has it's origin in business, where it it used to illustrate how a few high cost products can create as much or more profit than all the top top-sellers combined. Even though there is a low probability of purchase, the developing these products pay out. Over time, this term has been adopted by the advanced computing community. In this context, the long tail of science represents research projects enabled by HPC resources, science gateways, software, and expert support. We live in the data-age, but data on it's own doesn't provide us directly with knowledge. It takes transformation, analysis, visualization, machine learning, simulation, and modeling to transform data into scientific insight. As data get bigger or more fine-grained, so does the need for computational resources in small laboratories without their own advanced cyberinfrastructure. These small labs occupy the long tail, and if we can invest in providing them with HPC resources, there's no telling how high the payout will be. One goal of this podcast is to share the success stories of computing enabled research. The other is to raise the visibility of women in the field. Women are highly under-represented in HPC and we want to make role models in the field more conspicuous. 